# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Overtiome_development
  username: postgres
  password: "omnipod"
  
test:
  <<: *default
  database: Overtiome_test
  username: postgres
  password: "omnipod"


production:
  <<: *default
  database: Overtiome_production
  username: Overtiome
  password: <%= ENV['OVERTIOME_DATABASE_PASSWORD'] %>
